name: developer_assignment_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.9
  google_fonts: 6.1.0
  intl: 0.18.1
  table_calendar: 3.0.9
  shared_preferences: 2.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

